name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PRINCIPIA_HEADERS_GOOGLETEST: google????/include
  PRINCIPIA_MSVC_GOOGLETEST: google????/msvc

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3

    - name: Download glog artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: glog

    - name: Rebuild ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/rebuild@main
      with:
        configuration: ${{ matrix.configuration }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_GOOGLETEST }}

    - name: Upload artifact
      uses: mockingbirdnest/actions/windows/upload_artifact@main
      with:
        name: googletest
        headers_directory: ${{ env.PRINCIPIA_HEADERS_GOOGLETEST }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_GOOGLETEST }}
